penumbra-zone/galileo

.cargo/config
.github/workflows/rust.yml
.github/workflows/schedule.yml
Cargo.toml
config
src/wallet.rs

this PR:
* closes #4, which were preventing building this repo
* updates the syntax to use the new `TransactionPlan` (the `build_send` method we were using no longer exists so this was necessary)
* after sending a transaction, we now sleep for a block such that we avoid note reuse (temporary until the wallet refactor is complete)
* adds a basic CI integration running on push and PR (same as the other repos)
* adds a daily CI job that will build galileo versus latest Penumbra to alert us if we need to make updates

fixing the faucet for the Pandia testnet

---

Cargo.toml
src/opt/serve.rs

The testnet release process involves updating Galileo's Cargo.toml for the most recent testnet tag. While it's grand to have a 1:1 correspondence between Galileo's deps and the testnet version it handles disbursements for, it's quite tedious to bump the deps every week. Let's try tracking main branch, instead. Ultimately we aim to automate the build and rollout of galileo updates, but for now, a human's attention is still required.
We aren't committing `Cargo.lock` in this repo (should we?), so no diff for that file. Towards #17.

build: track upstream main branch, not tag

---

Cargo.toml
src/opt/serve.rs
src/wallet.rs

Recent migration to Account Groups requires some changes to Galileo: https://github.com/penumbra-zone/penumbra/pull/1994
Also requires Penumbra changes in https://github.com/penumbra-zone/penumbra/pull/2018

fix: source address handling

---

.github/workflows/rust.yml
.github/workflows/schedule.yml
Cargo.toml
README.md

We recently started using git-lfs in the penumbra repo, and cargo can't fetch lfs artifacts via a git dependency. For now, we'll clone the penumbra repo side-by-side and build from relative path.
Refs #29.

build: set penumbra deps as relative path

---

Cargo.toml
src/opt/history.rs

Follow up to recent account/proto changes. We haven't been running the history command regularly, so it broke during the great serialization transition. The address was being emitted as a b64 string, but we have a display impl that renders it as bech32 readable. Recasting as a string in order to take advantage of that. I'm sure there's a smarter way to do this, but I couldn't get serde's `serialize_with` to play nicely with the non-associated type within my timebox.
Also moved from `csv_stream` -> `csv` in an effort to use well-tested dependencies and focus on the bug in our code, not some other library's.

fix: history address serialization

---

src/sender.rs

Corresponds to changes in [0], which shipped as part of v0.51.1 for penumbra.
[0] https://github.com/penumbra-zone/penumbra/pull/2405

build: make account group id optional

---

.dockerignore
Containerfile

Builds a container image for Galileo, so we don't have to build it from source on every deployment. Similar in approach to the recently merged container spec for Osiris: https://github.com/penumbra-zone/osiris/pull/7

ci: add containerfile

---

.github/workflows/rust.yml

We were running cron schedule for `cargo check` and `cargo fmt`, but the fmt action won't catch compile errors from broken path dependencies. Let's run a full release build and ensure that passes. Refs #50.

ci: add daily release builds

---

Cargo.toml
src/opt/history.rs
src/opt/serve.rs
src/responder.rs
src/responder/request.rs
src/responder/response.rs
src/sender.rs
src/wallet.rs

We abolished the crypto crate as part of Testnet 56, so we must update our imports accordingly. Matches changes described in https://github.com/penumbra-zone/penumbra/issues/2765

chore: update penumbra deps layout

---

Cargo.toml
src/opt/serve.rs

We were missing a tonic dep that adds support for speaking HTTPS over gRPC. No code changes are required: updating the deps and rebuilding is all that's required.
Closes #48.

fix: support https for grpc

---

src/opt/history.rs

The bot replies with address info in its own messages. We now exclude those galileo-sent messages when building the history. First noticed this in catchup, but fixing it in history also solves for "history" subcommand.
Closes #57.

fix: skip galileo messages in history

---

.github/workflows/container.yml
Containerfile

Permits building a galileo container image using a specific tagged release of Penumbra. Important to ensure that service restarts don't pull a more recent container that's incompatible.
Closes #60

build: support explicit penumbra versions

---

.gitignore
src/responder/response.rs

With new website, the trailing slash is deleted

Update tx hash path

---

Cargo.toml

Matches changes in [0]. Bump was not broken, as was the case with Osiris [1], but bumping the dep anyway for consistency across the codebase.
[0] https://github.com/penumbra-zone/penumbra/pull/3192
[1] https://github.com/penumbra-zone/osiris/pull/25

chore: bump tonic 0.9 -> 0.10

---

src/responder/request.rs

The bech32m format requires a 1 to separate the human-readable prefix from the rest of the address info. Follow-up to [0]
[0] https://github.com/penumbra-zone/galileo/pull/69

fix: insert hrp separator

---

src/opt/serve.rs
src/responder.rs

Even though the sender service was made concurrent, the responder was still working serially. This spawns a new tokio task for each responder request, which will then use the load balanced sender services.

Use tokio tasks for each responder call

---

Cargo.toml
Containerfile
src/opt/serve.rs
src/responder.rs
src/wallet.rs

Reverts recent changes from #76. Changes:
* switches from in-memory db to on-disk view db
* updates the custody file format, to match https://github.com/penumbra-zone/penumbra/pull/3239
We've seen very slow syncing behavior on Galileo, so service restarts can block the faucet for ~15m. By using an on-disk db, we'll cache chain scans to keep restarts snappy.
Separate logic required to manage state between chain rollovers. We can do that in the deployment logic.

Use persistent view db

---

.github/workflows/rust.yml

Galileo only needs to work against the currently deployed testnet, but right now we only build against current main, which equates to the "preview" deployment of Penumbra. Let's differentiate the CI check to make them more informative, helping to catch build errors before the next release.

ci: build against preview & testnet

---

src/responder/response.rs

The error rate for Galileo has been quite high, due to volume of requests, so let's stop pinging admins via mention.

feat: don't mention admins on error

---

flake.nix

see penumbra-zone/penumbra#4496.
this is a replication of the seame change; adding rocksdb as a build input, and setting an environment variable to point the penumbra repository's `librocksdb-sys` dependency's build script at that package's static library.
this spares our builds the task of compiling the rocksdb database from source.

flake: 🪨 improve incremental builds by linking to rocksdb

---

.cargo/config.toml
Cargo.toml
src/opt/serve.rs
src/sender.rs

During Testnet 77 we enabled fees [0] and in the process broke some things like Galileo. Adding FeeTier support is rather straightforward, although this changeset requires a patch to the `penumbra-fee` crate in order to compile [1].
[0] https://github.com/penumbra-zone/penumbra/issues/4306
[1] https://github.com/penumbra-zone/penumbra/pull/4539

fix: add FeeTier support to galileo tx sending

---

src/handler.rs
src/tracing.rs

For reasons I don't understand, Galileo can fail to create a MessageInfo object from a Message. If that conversion fails, we can't proceed. The  unwrap was causing a fatal error; instead, let's just log it and keep going. Closes #101.
While I was in there, also patched up the logging, to make the logs easier to read when searching. Therefore closes #87.

fix: don't hard-error on unreadable messages

---

Cargo.toml

fixes #104. see penumbra-zone/penumbra#4582.
* penumbra-zone/penumbra#4582
* #104
@conorsch reported this error, when upgrading to a new testnet release:
> While performing the upgrade to Testnet 78
> ([penumbra-zone/penumbra#4582](https://github.com/penumbra-zone/penumbra/issues/4582))
> today, I noticed belated that Galileo isn't building against that
> version of the Penumbra monorepo. See example build failure here:
> https://github.com/penumbra-zone/galileo/actions/runs/9683427186/job/26718838171
>
> ```
> #20 226.5 error[E0277]: the trait bound `rustls_acme::axum::AxumAcceptor: Accept<hyper::server::tcp::addr_stream::AddrStream, _>` is not satisfied
> #20 226.5    --> src/opt/rpc.rs:115:44
> #20 226.5     |
> #20 226.5 115 | …
```

manifest: 🔨 fix build against v0.78.0 release
